# Modified version of hsrb_commong_config/params/hsrb_controller_config.yaml
# Because of typo's (ture instead of true)
hardware:
  publish_rate: 100

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

servo_state_controller:
  type: tmc_realtime_controllers/ServoStateController
  publish_rate: 50

omni_base_controller:
  type: hsrb_base_controllers/OmniBaseController
  base_coordinates:
    - odom_x
    - odom_y
    - odom_t
  joints:
    l_wheel: base_l_drive_wheel_joint
    r_wheel: base_r_drive_wheel_joint
    steer: base_roll_joint
  constraints:
    stopped_velocity_tolerance: 0.0
    odom_x:
      trajectory: 0.05
    odom_y:
      trajectory: 0.05
    odom_t:
      trajectory: 0.1
  stop_trajectory_duration: 1.0
  use_laser_odom: true
  wheel_odom_map_frame: odom
  wheel_odom_base_frame: base_footprint

  # these are described in hsrb_base_controllers/README.md
  steer_joint: base_roll_joint
  left_wheel_joint: base_l_drive_wheel_joint
  right_wheel_joint: base_r_drive_wheel_joint
  tread: 0.266
  caster_offset: 0.11
  wheel_radius: 0.040
  odom_x:
    p_gain: 1.0
  odom_y:
    p_gain: 1.0
  odom_t:
    p_gain: 1.0
  yaw_velocity_limit: 1.8      # [rad/s]
  wheel_velocity_limit: 8.5    # [rad/s]

drive_mode_controller:
  type: tmc_realtime_controllers/ExxxDriveModeController
  publish_rate: 50

servo_parameter_reader:
  type: tmc_realtime_controllers/InfrequentReadingController

servo_parameter_writer:
  type: tmc_realtime_controllers/InfrequentWritingController
  denied_keys:
    - const_id
    - command_write_nvm

head_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - head_tilt_joint
    - head_pan_joint
  constraints:
    stopped_velocity_tolerance: 0.5
    goal_time: 0.05
    head_tilt_joint:
      goal: 0.2

arm_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm_lift_joint
    - arm_flex_joint
    - arm_roll_joint
    - wrist_flex_joint
    - wrist_roll_joint
  constraints:
    stopped_velocity_tolerance: 0.5
    goal_time: 0.05

gripper_controller:
  type: hsrb_gripper_controller/HrhGripperController

  # these are described in hsrb_gripper_controller/README.md
  joints:
    - hand_motor_joint
  follow_joint_trajectory_action_monitor_rate: 20
  grasp_action_monitor_rate: 20
  apply_force_action_monitor_rate: 20
  force_calib_data_path: /etc/opt/tmc/robot/conf.d/calib_results/hand_force_params.yaml
  position_goal_tolerance: 0.2

imu_sensor_controller:
  type: imu_sensor_controller/ImuSensorController
  publish_rate: 100

collision_detection_controller:
  type: hsrb_collision_detection_controller/HsrbCollisionDetectionController
  joints:
    - arm_flex_joint
    - arm_lift_joint
    - arm_roll_joint
    - base_l_drive_wheel_joint
    - base_roll_joint
    - base_r_drive_wheel_joint
    - head_pan_joint
    - head_tilt_joint
    - wrist_flex_joint
    - wrist_roll_joint
  drivers:
    arm_flex_joint:
      names:
        - Current
        - Effort
      settings:
        Current: {enable: true, min: -1.2, max: 1.2, limit: 1.5}
        Effort: {enable: false, min: -19.4, max: 19.4, limit: 24.3}
    arm_lift_joint:
      names:
        - Current
        - Effort
      settings:
        Current: {enable: true, min: -1.4, max: 1.4, limit: 2.1}
        Effort: {enable: false, min: -407.5, max: 407.5, limit: 611.3}
    arm_roll_joint:
      names:
        - Current
        - Effort
      settings:
        Current: {enable: true, min: -0.87, max: 0.87, limit: 1.0}
        Effort: {enable: false, min: -4.8, max: 4.8, limit: 5.5}
    base_l_drive_wheel_joint:
      names:
        - Current
        - Effort
      settings:
        Current: {enable: true, min: -1.4, max: 1.4, limit: 4.3}
        Effort: {enable: false, min: -3.8, max: 3.8, limit: 11.6}
    base_roll_joint:
      names:
        - Current
        - Effort
      settings:
        Current: {enable: true, min: -1.49, max: 1.49, limit: 3.3}
        Effort: {enable: false, min: -8.2, max: 8.2, limit: 18.1}
    base_r_drive_wheel_joint:
      names:
        - Current
        - Effort
      settings:
        Current: {enable: true, min: -1.4, max: 1.4, limit: 4.3}
        Effort: {enable: false, min: -3.8, max: 3.8, limit: 11.6}
    head_pan_joint:
      names:
        - Current
        - Effort
      settings:
        Current: {enable: true, min: -0.87, max: 0.87, limit: 1.0}
        Effort: {enable: false, min: -1.6, max: 1.6, limit: 1.8}
    head_tilt_joint:
      names:
        - Current
        - Effort
      settings:
        Current: {enable: true, min: -0.87, max: 0.87, limit: 1.0}
        Effort: {enable: false, min: -5.7, max: 5.7, limit: 6.5}
    wrist_flex_joint:
      names:
        - Current
        - Effort
      settings:
        Current: {enable: true, min: -0.87, max: 0.87, limit: 1.0}
        Effort: {enable: false, min: -4.6, max: 4.6, limit: 5.2}
    wrist_roll_joint:
      names:
        - Current
        - Effort
      settings:
        Current: {enable: true, min: -0.87, max: 0.87, limit: 1.0}
        Effort: {enable: false, min: -4.6, max: 4.6, limit: 5.2}
  publish_rate: 25

tmc_diagnostic_controller:
  type: tmc_realtime_controllers/DiagnosticController
  publish_rate: 1
  message_max_length: 500

