#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

sudo cp $DIR/*.service /etc/systemd/system/

# Reload and enable
sudo systemctl daemon-reload
sudo systemctl start roscore.service
sudo systemctl start amigo-start.service
sudo systemctl enable roscore.service
sudo systemctl enable amigo-start.service

echo "Check the journal for the log"
echo "sudo journalctl -u [job_name, e.g. roscore, amigo-start]"
