#! /usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

sudo cp $DIR/hero-demo-mode.service /etc/systemd/system/

# Reload and enable
sudo systemctl daemon-reload
sudo systemctl start hero-demo-mode.service
sudo systemctl enable hero-demo-mode.service

echo "Check the journal for the log"
echo "sudo journalctl -fu [job_name, e.g. hero-demo-mode.service]"
