name: CI

on: [push, pull_request]

jobs:
  tue-ci:
    name: TUe CI - ${{ github.event_name }}
    runs-on: ubuntu-latest
    steps:
      - name: TUe CI
        uses: tue-robotics/tue-env/ci/main@gh_actions_use_ssh
        with:
          package: ${{ github.event.repository.name }}
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}
          ssh-known-hosts: github.com
